### PR TITLE
fix(sequelize): add support for extended operators in sequelize

### LINKED ISSUE #10272: [@loopback/sequelize] contains & match (extendedOperators) are not working
### Describe the bug

image
image
image
image

Also for ExtendedOperator (Match), 
**There is no equivalent operator for "match" in sequelize.** 

We're using it like : 
```
/localhost:4005/app-facade/tenants/f5408ba4-521f-4f96-fe87-bf0e6092ea16/patients/encounters?encountersType=both&filter={"limit":50,"where":{"and":[],"fullName":{"match":"%jiya:*&%"}}}
```

25%22%7D%7D%7D&encountersType=both Completed in 27ms
[2023-12-22T08:50:39.993Z] error :: App_Log -> Request GET /tenants/f5408ba4-521f-4f96-fe87-bf0e6092ea16/patients/encounters/count?filter=%7B%22where%22%3A%7B%22and%22%3A%5B%5D%2C%22fullName%22%3A%7B%22match%22%3A%22%25jiya%3A%2A%26%25%22%7D%7D%7D&encountersType=both errored out. Error :: {} Error: There is no equivalent operator for "match" in sequelize.
Request GET /tenants/f5408ba4-521f-4f96-fe87-bf0e6092ea16/patients/encounters/count?filter=%7B%22where%22%3A%7B%22and%22%3A%5B%5D%2C%22fullName%22%3A%7B%22match%22%3A%22%25jiya%3A%2A%26%25%22%7D%7D%7D&encountersType=both failed with status code 500. Error: There is no equivalent operator for "match" in sequelize.

### Logs

image

### Additional information

_No response_

### Reproduction

the issue is obvious and the provided information is enough to understand the problem.

### PR DESCRIPTION
**Pull request by yeshamavani**
postgres supports extended operators but missing in sequelize

fix #10272

**Please provide a high-level description of the changes made by your pull request.**
postgres supports extended operators but missing in sequelize
added the supported operators 
also the array field was by default given integer[] type even if it was string[].
added to condition to check before giving a default value.

Include references to all related GitHub issues and other pull requests, for example:

Fixes #10272

Example app to test - https://github.com/yeshamavani/sequelize

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by samarpanB — COMMENTED** [review]
can you please add a test case to it ?

**Comment by yeshamavani** [comment]
> can you please add a test case to it ?

added..

File: extensions/sequelize/src/__tests__/fixtures/controllers/roles.controller.ts [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+  @response(200, {
+    description: 'Role model instance',
+    content: {
+      'application/json': {
+        schema: getModelSchemaRef(Roles, {includeRelations: true}),
+      },
+    },
+  })
+  async getRolesByDesc(): Promise<Roles[]> {
+    return this.roleRepository.find({
```
Comment (samarpanB) [inline extensions/sequelize/src/__tests__/fixtures/controllers/roles.controller.ts:52]: Its better to pass this as where clause from test case

**Review by samarpanB — CHANGES_REQUESTED** [review]

File: extensions/sequelize/src/__tests__/fixtures/controllers/roles.controller.ts (hunk 1 above)
Comment (yeshamavani) [reply extensions/sequelize/src/__tests__/fixtures/controllers/roles.controller.ts]: done

**Review by samarpanB — APPROVED** [review]
